### PR TITLE
Updated Citation and Patch

### PR DESCRIPTION
**Pull request by mclark58**
fixed the citation format and increased the patch number

### CODE REVIEW

**Comment by dcchivian** [comment]
@mclark58 please describe what you changed in RELEASE_NOTES.md

**Comment by mclark58** [comment]
updated!

**Comment by dcchivian** [comment]
@sychan @scanon @psdehal I don't have merge permission on this repo.  Please merge @mclark58 changes.

**Comment by mclark58** [comment]
@sychan, should be good to go! :)

**Pull request merged**
